[wokwi]
version = 1
# MicroPython firmware files (local) so the CLI accepts a firmware path
firmware = "firmware/ESP32_GENERIC-20250911-v1.26.1.bin"
elf = "firmware/ESP32_GENERIC-20250911-v1.26.1.elf"

# Optional: forward serial to TCP if you prefer external monitor
# rfc2217ServerPort = 4000

[net]
# Using Public/Private Gateway handled by Wokwi. No port forwards needed for egress.

[fs]
"/main.py" = "main.py"
"/boot.py" = "boot.py"
"/config.json" = "config.json"
